#!/usr/bin/env ruby

require 'exif_datify'
require 'find'

raise "First argument must be a file or a directory path." unless ARGV.size == 1

date_extractor = ExifDatify::DateExtractor.new

if File.directory?(ARGV[0])
	Find.find(ARGV[0]) do |entry|
		next if FileTest.directory?(entry)
		begin
			date_extractor.rename(entry)
		rescue StandardError => e
			puts "Error: #{e}"
		end
	end
	puts "Processed #{date_extractor.counters[:total]} files, renamed #{date_extractor.counters[:renamed]}"
else
	date_extractor.rename(ARGV[0])
end
